name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact:
        description: 'Artifact name'
        type: string
        required: true
        default: dist
    secrets:
      some-secret:
        description: 'A secret'
        required: true
    outputs:
      result:
        description: 'The result'
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step_result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
      - name: Deploy
        run: echo "Deploying..."
      - name: Output information
        id: set-result
        run: |
          echo "Deployed!"
          echo "step_result=deployed" >> $GITHUB_OUTPUT